import jenkins.model.*
import hudson.security.*
def instance = Jenkins.getInstance()
def hudsonRealm = new HudsonPrivateSecurityRealm(false)
hudsonRealm.createAccount("admin","${user_pwd_admin}")
instance.setSecurityRealm(hudsonRealm)
hudsonRealm.createAccount("writer","${user_pwd_writer}")
instance.setSecurityRealm(hudsonRealm)
hudsonRealm.createAccount("reader","${user_pwd_reader}")
instance.setSecurityRealm(hudsonRealm)
def strategy = new GlobalMatrixAuthorizationStrategy()
//strategy.setAllowAnonymousRead(false)
strategy.add(Jenkins.ADMINISTER, "admin")
strategy.add(hudson.model.Hudson.READ,'admin')
//strategy.add(Jenkins.ADMINISTER, "writer")
//strategy.add(Jenkins.ADMINISTER, "reader")

strategy.add(hudson.model.Item.BUILD,'writer')
strategy.add(hudson.model.Item.CANCEL,'writer')
strategy.add(hudson.model.Item.CONFIGURE,'writer')
strategy.add(hudson.model.Item.CREATE,'writer')
strategy.add(hudson.model.Item.DELETE,'writer')
strategy.add(hudson.model.Item.DISCOVER,'writer')
strategy.add(hudson.model.Item.READ,'writer')
strategy.add(hudson.model.Item.WORKSPACE,'writer')
strategy.add(hudson.model.View.CONFIGURE,'writer')
strategy.add(hudson.model.View.CREATE,'writer')
strategy.add(hudson.model.View.DELETE,'writer')
strategy.add(hudson.model.View.READ,'writer')
strategy.add(hudson.model.Hudson.READ,'writer')

strategy.add(hudson.model.Item.READ,'reader')
strategy.add(hudson.model.View.CONFIGURE,'reader')
strategy.add(hudson.model.View.CREATE,'reader')
strategy.add(hudson.model.View.DELETE,'reader')
strategy.add(hudson.model.View.READ,'reader')
strategy.add(hudson.model.Hudson.READ,'reader')
instance.setAuthorizationStrategy(strategy)
instance.save()
