---
  - name: Install java and gnupg
    package:
      name: "{{ item }}"
      update_cache: yes
    with_items: "{{ packages }}"

  - name: Ensure the jenkins apt repository key is installed 
    apt_key:
      url: "{{jenkins.gpg_key}}" 
      state: present

  - name: Ensure the repository is configured
    apt_repository:
      repo: "{{jenkins.repo_URL}}" 
      state: present

  - name: Ensure jenkins is installed 
    apt:
      name: jenkins
      state: present
      update_cache: yes

  - name: Configure JVM Arguments
    lineinfile:
      dest: /etc/default/jenkins
      regexp: '^JAVA_ARGS='
      line: "{{ jenkins.JAVA_OPTIONS }}" 
      insertbefore: '^DAEMON_ARGS='

  - name: Create directory init.groovy.d
    file:
      path: /var/lib/jenkins/init.groovy.d
      state: directory
      owner: root
      group: root
      mode: '0755'

  - name: Copy disable csrf groovy  files
    copy:
      src: "{{ role_path }}/files/disable-csrf-protection.groovy"
      dest: /var/lib/jenkins/init.groovy.d/disable-csrf-protection.groovy
      mode: 0644

  - name: Copy csrf groovy  files
    copy:
      src: "{{ role_path }}/files/csrf.groovy"
      dest: /var/lib/jenkins/init.groovy.d/csrf.groovy
      mode: 0644
